name: travelapp
version: 1.0.0+1
publish_to: none
description: a flutter projects for bookin travel place
environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_it: ^7.2.0
  pretty_dio_logger: ^1.3.1
  flutter_secure_storage: ^8.0.0
  formz: ^0.6.1
  google_fonts: ^4.0.3
  hexcolor: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  assets_gen: ^1.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/titleicon.png
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700

import_sorter:
  emojis: true
  comments: true
